nodeLinker: node-modules

enableScripts: false

npmMinimalAgeGate: 4320

npmScopes:
  swan-bitcoin:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
