name: CI

on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@swan-bitcoin'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn workspaces foreach -A run compile
      - name: Run tests
        run: yarn workspaces foreach -A run test
