name: CI

on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@swan-bitcoin'
      - name: Install dependencies 
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn workspaces run compile
      - name: Run tests 
        run: yarn workspaces run test
