name: Publish Package to Github Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      packages: write
    env:
      SWAN_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@swan-bitcoin'
      - run: yarn install --immutable
      - run: yarn workspaces foreach -A run compile
      # publish xpub-lib
      - run: yarn workspace @swan-bitcoin/xpub-lib npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # publish xpub-cli
      - run: yarn workspace @swan-bitcoin/xpub-cli npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
